name: Run Tests on Dispatch

on:
  repository_dispatch:
    types: [tc001, tc002, tc003, all]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      TEST_CASE: ${{ github.event.action }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build Maven project
        run: mvn clean compile

      - name: Run tests via TestHarness
        run: mvn exec:java -Dexec.mainClass="com.example.TestHarness"

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: target/surefire-reports/
