name: Run TestHarness Based on Input

on:
  repository_dispatch:
    types: [tc001, tc002, tc003]

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # ✅ Required

      - name: Build with Maven
        run: mvn clean package


      - name: Run test case
        run: java -jar target/test-runner-0.0.1-SNAPSHOT-shaded.jar
        env:
            TEST_CASE: ${{ github.event.action }}


