name: Run Tests and Upload Report

on:
  repository_dispatch:
    types: [tc001, tc002, tc003, all]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      TEST_CASE: ${{ github.event.action }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and run tests
      run: |
        mvn clean test

    - name: Upload test report
      if: always()  # ensure this runs even if tests fail
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: target/surefire-reports/
