name: Run Automation Test

on:
  repository_dispatch:
    types: [tc001, tc002, tc003, run-all]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'  # ✅ Required

    - name: Set test case environment
      run: echo "TEST_CASE=${{ github.event.action }}" >> $GITHUB_ENV

    - name: Build and Run Test
      run: |
        mvn clean compile exec:java -Dexec.mainClass="com.testautomation.TestHarness"
